### ISSUE TITLE
It can not work with syntastic

### ISSUE THREAD

**Issue by snowair** [mtth/locate.vim#2]
If you have installed the [syntastic plugin](https://github.com/crooloose/syntastic) , the locate.vim will not show the choosen list window.

**Comment by mtth** [comment]
Hey, sorry for the long response delay. I see your `.vimrc` has different settings for GUI / terminal Vim, is this an issue in both?

**Comment by morganprecision** [comment]
Having the same issue ... also on MacOS (Yosemite).

The issue affects both gVim (MacVim) and terminal Vim.

Screenshot:
<img width="882" alt="screen shot 2015-10-21 at 3 18 37 pm" src="https://cloud.githubusercontent.com/assets/377314/10649022/50e29012-7807-11e5-8510-0936649379c1.png">

**Comment by morganprecision** [comment]
Forgot to mention that removing Syntastic fixes the issue.

**Comment by mtth** [comment]
@morganprecision - Could you share your syntastic and locate settings?

**Comment by morganprecision** [comment]
These are the only settings I have:

```
if has("win32") || has("win64")
    let g:syntastic_error_symbol = '⮀'
else
    let g:syntastic_error_symbol = '✗'
endif
let g:syntastic_warning_symbol = '!'

" PHP code sniffer
if (filereadable("phpcs.xml"))
    let g:syntastic_php_phpcs_args='--standard=phpcs.xml'
endif

" Syntastic - aggregate errors
let g:syntastic_aggregate_errors = 1
```

**Comment by mtth** [comment]
Thanks! So after digging into it a bit, I believe the conflict comes from syntastic's `g:syntastic_auto_loc_list` option which hijacks the location list (in particular closing it automatically when there are no errors, conflicting with locate).

Could you try adding the following line to your `.vimrc` and let me know if it changes anything:

```viml
let g:syntastic_auto_loc_list = 0
```

**Comment by morganprecision** [comment]
That fixed it! Thanks so much!

**Comment by mtth** [comment]
Glad to hear :). Closing this since it'll be hard to find a clean for fix this on the locate side unfortunately. Hopefully disabling the above option will cover most use-cases.
